export const USER_SUCCESSFULLY_CREATED = 'USER_SUCCESSFULLY_CREATED';
export const USER_ERROR_CREATED = 'USER_ERROR_CREATED';
export const AUTHENTICATED_USER_FETCHED_SUCCESS =
  'AUTHENTICATED_USER_FETCHED_SUCCESS';
export const AUTHENTICATED_USER_FETCHED_ERROR =
  'AUTHENTICATED_USER_FETCHED_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
